### ISSUE TITLE
pandas.errors.ParserError: Error tokenizing data. C error: Expected 10 fields in line 3, saw 11

### ISSUE THREAD

**Issue by ericries** [pwenker/chessli#26] opened 2022-08-07 05:38 UTC
I'm new to chessli, running it on MacOS. When I run chessli tactics ankify I get:

🔥 CHESSLI TACTICS 🔥

[22:36:48] INFO     Fetching new puzzle activity...                                                                              tactics.py:28
[22:36:57] INFO     There are 176 new puzzles!                                                                                   tactics.py:95
           INFO     Trying to read the most up-to-date lichess puzzle database from                                              tactics.py:38
                    https://database.lichess.org/lichess_db_puzzle.csv.bz2. This may take a few seconds...                                    
Traceback (most recent call last):
  File "/opt/homebrew/bin/chessli", line 8, in <module>
    sys.exit(app())
  File "/opt/homebrew/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/homebrew/lib/python3.9/site-packages/chessli/cli/tactics.py", line 70, in ankify
    tactics_manager.ankify_puzzles()
  File "/opt/homebrew/lib/python3.9/site-packages/chessli/tactics.py", line 158, in ankify_puzzles
    puzzles_df = self.read_lichess_puzzle_database()
  File "/opt/homebrew/lib/python3.9/site-packages/chessli/tactics.py", line 41, in read_lichess_puzzle_database
    puzzle_df = pd.read_csv(url, names=column_names, compression="bz2")
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1254, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 805, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 10 fields in line 3, saw 11

any help is much appreciated

**Comment by jpfreiire** [comment] 2022-11-17 10:19
i can't install chessli, if anyone can help me please contact me on discord pls flex[#3045](https://www.youtube.com/hashtag/3045)

**Comment by fedeoiu** [comment] 2023-03-06 14:48
I had a similar problem on linux. 
This line tells you where the problem is:

File "/opt/homebrew/lib/python3.9/site-packages/chessli/tactics.py", line 41, in read_lichess_puzzle_database
puzzle_df = pd.read_csv(url, names=column_names, compression="bz2")

Apparently lichess database file is not as pandas expects (last line says: pandas.errors.ParserError: Error tokenizing data. C error: Expected 10 fields in line 3, saw 11), because in some lines it has more columns.
In order to tell pandas to only read 9 columns even if more are present i added in line 41 of this file "/opt/homebrew/lib/python3.9/site-packages/chessli/tactics.py" the following command:

usecols=range(0, len(column_names)),

So line 41 should be something like:

puzzle_df = pd.read_csv(url, names=column_names, usecols=range(0, len(column_names)), compression="bz2")


(sorry for my english)

**Comment by pwenker** [comment] 2024-04-11 10:30
I am developing a new simplified version of chessli with a graphical user interface. 
This error will be fixed soon :)

**Closed by pwenker** 2024-04-11 10:30 UTC
